# 1. Introduction to Numpy

## 1.1 What is NumPy?

NumPy = Numerical Python

It is a Python library designed for:

1. Fast numerical computation
2. Working with arrays and matrices
3. Mathematical operations
4. Scientific computing

## 1.2 Why was numpy created 

Imagine storing:

[10, 20, 30, 40]

in a Python list.

A Python list does not store the actual integers directly in a compact block.

Instead, it stores references (addresses) to Python objects.

Simplified:
```
    List
    │
    ├──► Integer Object(10)
    ├──► Integer Object(20)
    ├──► Integer Object(30)
    └──► Integer Object(40)
```
This makes python list flexible:- 
1. Can store int
2. float
3. string
4. list
5. anything

But:

❌ More memory

❌ Slower numerical computation

NumPy says:

"If all data is of the same type, why waste memory?"

So NumPy stores data in a continuous memory block.

Simplified:

[10][20][30][40]

Benefits:

✅ Less memory

✅ Faster access

✅ Vectorized operations

✅ Used by Pandas, Scikit-Learn, TensorFlow, PyTorch

## 1.3 What Problem Does NumPy Solve?



### 1.3.1 Python List vs Numpy array 

Python List Problems
1. Slower computation
2. More memory usage
3. Not optimized for mathematical operations
4. Poor support for matrix operations

NumPy Solution
1. Faster computation
2. Less memory
3. Vectorized operations
4. Matrix and linear algebra support

### 1.3.2 What is Vectorization?

Performing operations on an entire array at once instead of processing elements one-by-one using loops.

#### Without Vectorization (Python List)

In [1]:


""" Suppose:"""

marks = [10,20,30,40]

""" You want to add 5 to every mark."""

new_marks = []

for i in marks:
    new_marks.append(i + 5)

print(new_marks)

[15, 25, 35, 45]


### 1.3.3 Why is NumPy faster than Python lists?

1. NumPy stores data in contiguous memory.
2. Arrays contain homogeneous data types.
3. Operations are implemented in optimized C code.
4. NumPy uses vectorized operations instead of Python-level loops.

# 2. Creating NumPy Array

A NumPy array is:

A collection of elements of the same data type stored efficiently in memory.

It converts Python data structures into a NumPy array.

1. doesn't have commas.
2. list have commas.

In [2]:
import numpy as np 

In [18]:
"Example 1"

print(np.array((1,2,3,4)))

""" NumPy stores these as: `int

"""

[1 2 3 4]


' NumPy stores these as: `int\n\n'

In [23]:
"Example 2"

a = np.array([1,2,"hello"])
print(a)
print(type(a))
print(a.dtype)


['1' '2' 'hello']
<class 'numpy.ndarray'>
<U21


In [ ]:
"""
What does <U21 mean?

Simplified:

U = Unicode String
21 = Maximum length allocated

The important part is:

NumPy converted everything into strings.

So internally it becomes:

array(['1', '2', 'hello'])
All elements now have the same datatype.

"""

"\nWhat does <U21 mean?\n\nSimplified:\n\nU = Unicode String\n21 = Maximum length allocated\n\nThe important part is:\n\nNumPy converted everything into strings.\n\nSo internally it becomes:\n\narray(['1', '2', 'hello'])\n\n"

In [25]:
np.array([1,2,True])

array([1, 2, 1])

## 2.1 1D array

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
type(a)

numpy.ndarray

## 2.2   2D Array

1. rows
2. columns

In [7]:
b = np.array([
    [1,2,3],
    [4,5,6]
])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


## 2.3 3D Array

Multiple 2D tables stacked together.

1. rows
2. columns
3. channels

rows X columns X channels

✅ Channel = one layer of information

✅ Multiple channels = multiple layers/tables stacked together

In [9]:
c = np.array([
    [[1,2,3]],
    [[4,5,6]]
])

print(c)
print(c.ndim)

[[[1 2 3]]

 [[4 5 6]]]
3


In [14]:
"Example 1"

np.array([
    [
        [1,2],[3,4]
    ],
    [
        [4,5],[7,8]
    ]

])

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [7, 8]]])

In [11]:
d = np.array([
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]]
])

print(d)
print(d.ndim)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


## 2.4. dtype
Data type

What type of values are stored inside the NumPy array?

 dtype stands for Data Type
- dtype is an attribute
- Used to check what type of data an array stores
- Common dtypes:
  - int32
  - int64
  - float32
  - float64

In [15]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [18]:
np.array([1,2,3,0],dtype=bool)

array([ True,  True,  True, False])

## 2.5 arange()

In [3]:
"Example 1"

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
"Example 2"

np.arange(1,11,2)

array([1, 3, 5, 7, 9])

## 2.6. reshape()

In [6]:
"Example 1"

np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
"Example 2"

np.arange(1,15).reshape(7,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

## 2.7. ones() and zeros()

In [15]:
"Exanple 1"

np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## 2.7 random

generates array between 0 to 1.

In [27]:
np.random.random((2,3))

array([[0.30160055, 0.24193075, 0.54016305],
       [0.29496857, 0.12761633, 0.47294071]])

## 2.9 linspace()

Creates equally spaced numbers.

```
Syntax:

np.linspace(start, stop, num_values)
```

In [31]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

```
start = 0
end   = 10
total values = 5
```

## 2.10 identity()



In [32]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 3. Array attributes

In [33]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [34]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

## 3.1 ndim

In [35]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


## 3.2 shape

In [38]:
print(a1.shape) # 10 elements

print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


## 3.3 size
Total number of elemets in an array.

In [39]:
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


## 3.4 itemsize

- int32 -> takes 4 bytes
- int64 -> takes 8 bytes
- float64 -> takes 8 bytes

In [42]:
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


## 3.4 dtype


In [44]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# 4. changing datatypes

## 1. astype

In [45]:
print(a1.dtype)

int64


In [48]:
a1.astype(np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

# 5. array operations 

In [50]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## 5.1 scalar operations

### 5.1.1 Arithmetic operations

In [51]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
a1 *2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [53]:
a1 +10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

###  5.1.2 Relational operation

In [54]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
a1 == 6

array([[False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [56]:
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

## 5.2 vector operation

### 5.2.1 Arithmetic operaton

In [58]:
print(a1)
print("\n")
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [60]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [61]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])