# 1. Introduction to Numpy

## 1.1 What is NumPy?

NumPy = Numerical Python

It is a Python library designed for:

1. Fast numerical computation
2. Working with arrays and matrices
3. Mathematical operations
4. Scientific computing

### Homogeneous Array

A NumPy array is homogeneous, which means all elements are stored as the same data type.

Example:

np.array([1,2,3])
- int64

np.array([1,2,3.5])
- float64

NumPy automatically converts data to a common type when needed.

## 1.2 Why was numpy created 

Imagine storing:

[10, 20, 30, 40]

in a Python list.

A Python list does not store the actual integers directly in a compact block.

Instead, it stores references (addresses) to Python objects.

Simplified:
```
    List
    │
    ├──► Integer Object(10)
    ├──► Integer Object(20)
    ├──► Integer Object(30)
    └──► Integer Object(40)
```
This makes python list flexible:- 
1. Can store int
2. float
3. string
4. list
5. anything

But:

❌ More memory

❌ Slower numerical computation

NumPy says:

"If all data is of the same type, why waste memory?"

So NumPy stores data in a continuous memory block.

Simplified:

[10][20][30][40]

Benefits:

✅ Less memory

✅ Faster access

✅ Vectorized operations

✅ Used by Pandas, Scikit-Learn, TensorFlow, PyTorch

## 1.3 What Problem Does NumPy Solve?



### 1.3.1 Python List vs Numpy array 

Python List Problems
1. Slower computation
2. More memory usage
3. Not optimized for mathematical operations
4. Poor support for matrix operations

NumPy Solution
1. Faster computation
2. Less memory
3. Vectorized operations
4. Matrix and linear algebra support

### 1.3.2 What is Vectorization?

Performing operations on an entire array at once instead of processing elements one-by-one using loops.

#### Without Vectorization (Python List)

In [1]:


""" Suppose:"""

marks = [10,20,30,40]

""" You want to add 5 to every mark."""

new_marks = []

for i in marks:
    new_marks.append(i + 5)

print(new_marks)

[15, 25, 35, 45]


### 1.3.3 Why is NumPy faster than Python lists?

1. NumPy stores data in contiguous memory.
2. Arrays contain homogeneous data types.
3. Operations are implemented in optimized C code.
4. NumPy uses vectorized operations instead of Python-level loops.

###  Contiguous Memory

NumPy stores elements in a continuous block of memory.

[10][20][30][40]

This allows faster access and computation compared to Python lists, which store references to objects.

# 2. Creating NumPy Array

A NumPy array is:

A collection of elements of the same data type stored efficiently in memory.

It converts Python data structures into a NumPy array.

1. doesn't have commas.
2. list have commas.

In [2]:
import numpy as np 

In [18]:
"Example 1"

print(np.array((1,2,3,4)))

""" NumPy stores these as: `int

"""

[1 2 3 4]


' NumPy stores these as: `int\n\n'

### ndarray

NumPy arrays are objects of type numpy.ndarray.

ndarray stands for n-dimensional array.

Examples:

- 1D Array
- 2D Array
- 3D Array

All are instances of numpy.ndarray.

In [23]:
"Example 2"

a = np.array([1,2,"hello"])
print(a)
print(type(a))
print(a.dtype)


['1' '2' 'hello']
<class 'numpy.ndarray'>
<U21


In [ ]:
"""
What does <U21 mean?

Simplified:

U = Unicode String
21 = Maximum length allocated

The important part is:

NumPy converted everything into strings.

So internally it becomes:

array(['1', '2', 'hello'])
All elements now have the same datatype.

"""

"\nWhat does <U21 mean?\n\nSimplified:\n\nU = Unicode String\n21 = Maximum length allocated\n\nThe important part is:\n\nNumPy converted everything into strings.\n\nSo internally it becomes:\n\narray(['1', '2', 'hello'])\n\n"

In [25]:
np.array([1,2,True])

array([1, 2, 1])

## 2.1 1D array

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
type(a)

numpy.ndarray

## 2.2   2D Array

1. rows
2. columns

In [7]:
b = np.array([
    [1,2,3],
    [4,5,6]
])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


## 2.3 3D Array

Multiple 2D tables stacked together.

1. rows
2. columns
3. channels

rows X columns X channels

✅ Channel = one layer of information

✅ Multiple channels = multiple layers/tables stacked together

In [9]:
c = np.array([
    [[1,2,3]],
    [[4,5,6]]
])

print(c)
print(c.ndim)

[[[1 2 3]]

 [[4 5 6]]]
3


In [14]:
"Example 1"

np.array([
    [
        [1,2],[3,4]
    ],
    [
        [4,5],[7,8]
    ]

])

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [7, 8]]])

In [11]:
d = np.array([
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]]
])

print(d)
print(d.ndim)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


## 2.4. dtype
Data type

What type of values are stored inside the NumPy array?

 dtype stands for Data Type
- dtype is an attribute
- Used to check what type of data an array stores
- Common dtypes:
  - int32
  - int64
  - float32
  - float64

In [15]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

### Type Promotion

When multiple datatypes are present, NumPy converts all values to the safest common datatype.

Examples:

bool -> int -> float -> string

[1,2,True]
=> int64

[1,2,3.5]
=> float64

[1,2,"hello"]
=> string

In [18]:
np.array([1,2,3,0],dtype=bool)

array([ True,  True,  True, False])

## 2.5 arange()

In [3]:
"Example 1"

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
"Example 2"

np.arange(1,11,2)

array([1, 3, 5, 7, 9])

## 2.6. reshape()

reshape() changes the dimensions of an array without changing the data.

Rule:

Total elements before reshape = Total elements after reshape

In [6]:
"Example 1"

np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
"Example 2"

np.arange(1,15).reshape(7,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

## 2.7. ones() and zeros()

In [ ]:
"Example 1"

np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [4]:
import numpy as np
print(np.zeros((3,4)))
np.zeros((3,4)).ndim

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


2

In [6]:
print(np.ones((3,3,3)))
print(np.ones((3,3,3)).ndim)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
3


In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## 2.7 random

generates array between 0 to 1.

In [27]:
np.random.random((2,3))

array([[0.30160055, 0.24193075, 0.54016305],
       [0.29496857, 0.12761633, 0.47294071]])

## 2.9 linspace()

Creates equally spaced numbers.

```
Syntax:

np.linspace(start, stop, num_values)
```

In [31]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

```
start = 0
end   = 10
total values = 5
```

## 2.10 identity()



In [32]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Special numpy array.

## 1.empty array

Creates an array without initializing values.

- Faster than zeros()
- Contains garbage values
- Useful when values will be overwritten later
- np.empty(5) is NOT an empty array.
- It is an uninitialized array of size 5.

Why Strange Values?

Because NumPy:

Allocates memory
BUT
Does not fill it

The memory may already contain old data.

```
Shape is: (5,)
It contains 5 memory locations.

A truly empty array is: np.array([])

or

np.empty(0)

Shape: (0,)
```

In [27]:
np.empty(0)
print(np.array([]))

[]


In [ ]:

np.empty((3,4,5))

## 2. arange()

In [29]:
np.arange(3,101,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69,
       71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

## 3. linspace()

```
Syntax
np.linspace(start, stop, num)
```

- start = starting value
- stop  = ending value
- num   = total values required

In [30]:
"Example 1"

np.linspace(2,10,4)

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])

# 3. Array attributes

In [33]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [34]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

## 3.1 ndim

In [35]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


## 3.2 shape

Shape returns the number of elements in each dimension.

Examples:

(10,)
=> 10 elements in a 1D array

(3,4)
=> 3 rows and 4 columns

(2,2,2)
=> 2 tables, 2 rows, 2 columns

In [38]:
print(a1.shape) # 10 elements

print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


## 3.3 size
Total number of elemets in an array.

In [39]:
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


## 3.4 itemsize

- int32 -> takes 4 bytes
- int64 -> takes 8 bytes
- float64 -> takes 8 bytes

In [42]:
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


## 3.4 dtype


In [44]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# 4. changing datatypes

## 1. astype

In [45]:
print(a1.dtype)

int64


In [48]:
a1.astype(np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

# 5. array operations 

In [50]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## 5.1 scalar operations

An operation performed between an array and a single value (scalar).

Examples:

- arr + 10
- arr * 2
- arr / 5


### 5.1.1 Arithmetic operations

In [51]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
a1 *2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [53]:
a1 +10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

###  5.1.2 Relational operation

In [54]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
a1 == 6

array([[False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [56]:
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

## 5.2 vector operation

An operation performed between arrays element-by-element without using explicit Python loops.

Example:

- a1 + a2
- a1 * a2

### 5.2.1 Arithmetic operaton

In [58]:
print(a1)
print("\n")
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [60]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [61]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# 6. Array functions

In [70]:
a1 = np.random.random((3,3))
a1

array([[0.080836  , 0.24121339, 0.86606011],
       [0.379428  , 0.05725945, 0.83347853],
       [0.5763723 , 0.66903083, 0.66562369]])

In [71]:

a1 = np.round(a1*100)


a1

array([[ 8., 24., 87.],
       [38.,  6., 83.],
       [58., 67., 67.]])

### Axis

Axis represents the direction along which an operation is performed.

For a 2D array:

axis = 0 -> column-wise operation

axis = 1 -> row-wise operation

## 6.1 max()

- axis = 0 -> columns
- axis = 1 -> rows

In [72]:
a1.max()

np.float64(87.0)

In [ ]:
a1.max(axis = 1)   # row wise maximum items 

array([87., 83., 67.])

## 6.2 min()



In [73]:
a1.min()

np.float64(6.0)

In [79]:
a1.min(axis = 0)

array([ 8.,  6., 67.])

## 6.3 sum()


In [74]:
a1.sum()

np.float64(438.0)

## 6.4 prod()

In [75]:
a1.prod()

np.float64(82302119511552.0)

## 6.5 mean()

In [82]:
a1

array([[ 8., 24., 87.],
       [38.,  6., 83.],
       [58., 67., 67.]])

In [ ]:
"Example 1"
np.mean(a1)

np.float64(48.666666666666664)

In [81]:
"Example 2"

np.mean(a1, axis=1)

array([39.66666667, 42.33333333, 64.        ])

## 6.6 median()

In [83]:
np.median(a1)

np.float64(58.0)

## 6.7 std() (standard deviation) 

In [84]:
np.std(a1)

np.float64(29.066972475455522)

## 6.8 var (varience)

In [85]:
np.var(a1)

np.float64(844.8888888888889)

In [87]:
"Example 1 "

np.var(a1, axis = 0)

array([422.22222222, 654.88888889,  74.66666667])

## 6.9 trigonometric functions

In [88]:
np.sin(a1)

array([[ 0.98935825, -0.90557836, -0.82181784],
       [ 0.29636858, -0.2794155 ,  0.96836446],
       [ 0.99287265, -0.85551998, -0.85551998]])

## 6.10 dot product

A mathematical operation between two arrays/matrices that combines multiplication and addition.

Condition:

(m × n) · (n × p)

Result:

(m × p)

- a1 = 3x4
- a2 = 4x3

Then the resultant dot product will be (3x3)

In [89]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [90]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

## 6.11 log and exponents

In [91]:
np.log(a2)

C:\Users\kshit\AppData\Local\Temp\ipykernel_22604\970536687.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a2)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [92]:
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

## 6.12 round()/floor()/ceil()

- round(6.9) = 7
- round(6.4) = 6
- floor(6.9) = 6 
- ceil(6.4) = 7

In [100]:
np.round(np.random.random((2,3))*100)

array([[64., 75., 24.],
       [33., 43., 44.]])

In [109]:
print(np.round(6.4))
print(np.round(6.9))

print(np.floor(6.4))
print(np.floor(6.9))

print(np.ceil(6.4))
print(np.ceil(6.6))
print(np.ceil(6.9))




6.0
7.0
6.0
6.0
7.0
7.0
7.0


# 7. indexing and slicing

## 7.1 indexing

Indexing is used to access a specific element from an array.

Examples:

- arr[0]
- arr[1,2]
- arr[0,1,2]

In [113]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)

1d array

In [114]:
a1 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
print(a1[0])
print(a1[-1])

0
9


2d array

- a2[row,col]

In [116]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
print(a2[0,0])
print(a2[1,1])
print(a2[2,3])

0
5
11


3d array

- a3[table, row, col]

In [123]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [128]:
print(a3[0,0,1])
print(a3[1,1,1])
print(a3[1,2,2])
print(a3[2,1,2])

1
13
17
23


## 7.2 Slicing

Slicing is used to extract a portion of an array.
```
Syntax:

array[start:stop:step]

array[row_start:row_stop, col_start:col_stop]
```

 1d array

In [129]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
print(a1[0:4])

[0 1 2 3]


In [133]:
print(a1[-4:])

[6 7 8 9]


2d array

- arr[0:1, :]: Grabs rows starting at 0 up to (but not including) 1.
- arr[0, :]: Grabs exactly row 0.

The general rule for 2D slicing
- sub_array = array[row_start:row_stop:jump, col_start:col_stop:jump]


In [134]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [152]:
print(a2[0:1,:])

[[0 1 2 3]]


In [158]:
print(a2[1,:])

[4 5 6 7]


In [157]:
print(a2[:,2])

[ 2  6 10]


In [154]:
print(a2[0,:])

[0 1 2 3]


In [156]:
print(a2[1:,2:])

[[ 6  7]
 [10 11]]


In [162]:
print(a2[1:,1:3])

[[ 5  6]
 [ 9 10]]


In [163]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [170]:
"i want 0,3,8,11"

print(a2[0::2,::3])

[[ 0  3]
 [ 8 11]]


In [172]:
"i want 1,3,9,11"

print(a2[::2,1::2])

[[ 1  3]
 [ 9 11]]


In [174]:
"i want 1,3,,5,7"

print(a2[:2,1::2])

[[1 3]
 [5 7]]


In [175]:
"i want 4, 7"

print(a2[1,::3])

[4 7]


3d array

In [176]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [177]:
print(a3[1])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [180]:
print(a3[::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
"i want only 1st row of 1st array"
print(a3[0,1,:])

[3 4 5]


In [182]:
"i want only 1st column of 2nd array"
print(a3[1,:,1])

[10 13 16]


In [184]:
"i want only 22 23 25 26"

print(a3[2,1:,1:])

[[22 23]
 [25 26]]


In [185]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [188]:
"i want 0, 2, 18, 20"

print(a3[::2,0,::2])

[[ 0  2]
 [18 20]]


# 8. Iterating

1d array

In [189]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [192]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


2d array

In [190]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [194]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


3d array

In [191]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [195]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


## iter()

In [197]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [198]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# 9. Transpose

Transpose converts rows into columns and columns into rows.

Shape:

(m,n) -> (n,m)

In [199]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [200]:
a2.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [201]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# 10. ravel()   and   flatten()
Both are used to convert a multi-dimensional array into a 1D array.

Converts a multi-dimensional array into a 1D array.

Returns a VIEW whenever possible.

In [35]:
"Example 1"

a = np.array([
    [1,2,3],
    [4,5,6]
])

print(np.ravel(a))
print(np.shape(a))

[1 2 3 4 5 6]
(2, 3)


In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [204]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [205]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [203]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

###  flatten()
Converts a multi-dimensional array into a 1D array.

Returns a VIEW whenever possible.

In [38]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

# 11. Stacking

- shape will be same 

## 11.1 horizontal stacking

- (2x2)(2x2) -> (2x4)

In [208]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [213]:
print(a4)
print("\n")
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [217]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

## 11.2 vertical stacking 

- (2x2)(2x2) -> (4x2)

In [220]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# 12. Splitting

In [221]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 12.1 Horizontal Splitting

In [225]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [226]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

## 12.2 Vertical Splitting

In [227]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [229]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]