# 1. Introduction to Numpy

## 1.1 What is NumPy?

NumPy = Numerical Python

It is a Python library designed for:

1. Fast numerical computation
2. Working with arrays and matrices
3. Mathematical operations
4. Scientific computing

## 1.2 Why was numpy created 

Imagine storing:

[10, 20, 30, 40]

in a Python list.

A Python list does not store the actual integers directly in a compact block.

Instead, it stores references (addresses) to Python objects.

Simplified:
```
    List
    │
    ├──► Integer Object(10)
    ├──► Integer Object(20)
    ├──► Integer Object(30)
    └──► Integer Object(40)
```
This makes python list flexible:- 
1. Can store int
2. float
3. string
4. list
5. anything

But:

❌ More memory

❌ Slower numerical computation

NumPy says:

"If all data is of the same type, why waste memory?"

So NumPy stores data in a continuous memory block.

Simplified:

[10][20][30][40]

Benefits:

✅ Less memory

✅ Faster access

✅ Vectorized operations

✅ Used by Pandas, Scikit-Learn, TensorFlow, PyTorch

## 1.3 What Problem Does NumPy Solve?



### 1.3.1 Python List vs Numpy array 

Python List Problems
1. Slower computation
2. More memory usage
3. Not optimized for mathematical operations
4. Poor support for matrix operations

NumPy Solution
1. Faster computation
2. Less memory
3. Vectorized operations
4. Matrix and linear algebra support

### 1.3.2 What is Vectorization?

Performing operations on an entire array at once instead of processing elements one-by-one using loops.

#### Without Vectorization (Python List)

In [1]:


""" Suppose:"""

marks = [10,20,30,40]

""" You want to add 5 to every mark."""

new_marks = []

for i in marks:
    new_marks.append(i + 5)

print(new_marks)

[15, 25, 35, 45]


### 1.3.3 Why is NumPy faster than Python lists?

1. NumPy stores data in contiguous memory.
2. Arrays contain homogeneous data types.
3. Operations are implemented in optimized C code.
4. NumPy uses vectorized operations instead of Python-level loops.

## 1.4 NumPy Array

A NumPy array is:

A collection of elements of the same data type stored efficiently in memory.

1. doesn't have commas.
2. list have commas.

In [2]:
import numpy as np 

### 1.4.1 1D array

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
type(a)

numpy.ndarray

### 1.4.2   2D Array

In [7]:
b = np.array([
    [1,2,3],
    [4,5,6]
])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


### 1.4.3 3D Array

In [9]:
c = np.array([
    [[1,2,3]],
    [[4,5,6]]
])

print(c)
print(c.ndim)

[[[1 2 3]]

 [[4 5 6]]]
3


In [11]:
d = np.array([
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]]
])

print(d)
print(d.ndim)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


## 1.5. dtype

In [15]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [18]:
np.array([1,2,3,0],dtype=bool)

array([ True,  True,  True, False])