# 1. Numpy array vs Python lists

## 1.1 speed

list

In [3]:
a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]

c = []
import time

start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])

end = time.time() - start
end

2.6902852058410645

array

In [ ]:
import numpy as np

In [6]:
c = np.arange(10000000)
d = np.arange(10000000,20000000)

start = time.time()
d = c+d
end = time.time() - start
end

0.04464983940124512

In [ ]:
print(2.69/0.04)

"array is 67 times faster than python list"


67.25


## 1.2 Memory

list

In [8]:
a = [i for i in range(10000000)]

import sys
sys.getsizeof(a)

89095160

In [11]:
b = np.arange(10000000, dtype=np.int32)

sys.getsizeof(b)

40000112

# 2. Advanced Indexing

## 2.1 Fancy indexing

In [14]:
a1 = np.arange(12).reshape(6,2)
a1

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [15]:
"i want 0th, 2nd, 3rd 5th row"

print(a1[[0,2,3,5]])

[[ 0  1]
 [ 4  5]
 [ 6  7]
 [10 11]]


In [16]:
a1[4,1:]

array([9])

In [17]:
a2 = np.arange(27).reshape(3,3,3)
a2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [28]:
a2[:,[0][:]]

array([[[ 0,  1,  2]],

       [[ 9, 10, 11]],

       [[18, 19, 20]]])

## 2.2 Boolean Indexing

## random.randint()

In [35]:
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[31, 62, 66, 44],
       [15, 87, 39,  9],
       [16, 66, 98, 94],
       [99, 21, 10, 22],
       [66, 65, 15, 72],
       [20, 14, 84, 65]], dtype=int32)

In [36]:
a > 50

array([[False,  True,  True, False],
       [False,  True, False, False],
       [False,  True,  True,  True],
       [ True, False, False, False],
       [ True,  True, False,  True],
       [False, False,  True,  True]])

In [38]:
a[a>50]


array([62, 66, 87, 66, 98, 94, 99, 66, 65, 72, 84, 65], dtype=int32)

In [ ]:
"Find out even numbers."

a[a % 2 == 0]

array([62, 66, 44, 16, 66, 98, 94, 10, 22, 66, 72, 20, 14, 84],
      dtype=int32)

In [44]:
"Find out numbers greater than 50 and also even. "

a[(a % 2 == 0) & (a>50)]

array([62, 66, 66, 98, 94, 66, 72, 84], dtype=int32)

In [46]:
a

array([[31, 62, 66, 44],
       [15, 87, 39,  9],
       [16, 66, 98, 94],
       [99, 21, 10, 22],
       [66, 65, 15, 72],
       [20, 14, 84, 65]], dtype=int32)

In [48]:
"Find numbers not divisible by 7."

a[a % 7 == 0]

array([98, 21, 14, 84], dtype=int32)

# 3. Broadcasting



Broadcasting is NumPy's mechanism for performing arithmetic operations on arrays of different shapes by automatically expanding the smaller array to match the shape of the larger array.

In [ ]:
import numpy as np

arr = np.array([1,2,3])

arr + 5


"""
5 -> [5,5,5]
[1,2,3] + [5,5,5] 

"""

array([6, 7, 8])

## 3.1 Broadcasting Rules

NumPy compares shapes from right to left.

Two dimensions are compatible if:

1. They are equal
OR
2. One of them is 1
```
(3, 2) (3,)
(3, 2)  (1,3)

(3, 3, 3) (3,)
(3, 3, 3) (1, 1, 3)
```

In [ ]:
"Example 1"
"""
(3,4)
(3,1)

Compare:

4 can expand from 1 ✔
3 == 3 ✔

Broadcasting works.
"""

In [ ]:
"Example 2"

"""
(3,4)
(2,4)

Compare:

4 == 4 ✔
3 ≠ 2 ✘

Broadcasting fails.
"""

## 3.2 Scalar Broadcasting

In [4]:
a = np.array([1,2,3,4])

print(a + 10)

# Output:

""" [11 12 13 14]"""

# Internally:
"""
[1 2 3 4]
+
[10 10 10 10]
"""

[11 12 13 14]


'\n[1 2 3 4]\n+\n[10 10 10 10]\n'

## 3.3 2D Array + Scalar

In [5]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

print(a + 100)

# Output:
"""
[[101 102 103]
 [104 105 106]]

Internally:

[
 [1 2 3]
 [4 5 6]
]

+

[
 [100 100 100]
 [100 100 100]
]
"""

[[101 102 103]
 [104 105 106]]


'\n[[101 102 103]\n [104 105 106]]\n\nInternally:\n\n[\n [1 2 3]\n [4 5 6]\n]\n\n+\n\n[\n [100 100 100]\n [100 100 100]\n]\n'

## 3.4 Row-wise Broadcasting

In [7]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

b = np.array([10,20,30])

print(a + b)

"""
Shapes:

a.shape -> (2,3)
b.shape -> (3,)

NumPy expands:

[10 20 30]

↓

[
 [10 20 30]
 [10 20 30]
]

Then adds.
"""

[[11 22 33]
 [14 25 36]]


'\nShapes:\n\na.shape -> (2,3)\nb.shape -> (3,)\n\nNumPy expands:\n\n[10 20 30]\n\n↓\n\n[\n [10 20 30]\n [10 20 30]\n]\n\nThen adds.\n'

## 3.5 Column-wise Broadcasting

In [8]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

b = np.array([
    [10],
    [20]
])

print(a + b)

"""
Shapes:

a.shape -> (2,3)
b.shape -> (2,1)

NumPy expands:

[
 [10]
 [20]
]

↓

[
 [10 10 10]
 [20 20 20]
]
"""

[[11 12 13]
 [24 25 26]]


'\nShapes:\n\na.shape -> (2,3)\nb.shape -> (2,1)\n\nNumPy expands:\n\n[\n [10]\n [20]\n]\n\n↓\n\n[\n [10 10 10]\n [20 20 20]\n]\n'

## Broadcasting Fails


In [ ]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

b = np.array([
    [10,20],
    [30,40]
])

print(a + b)

Q. Difference between Vectorization and Broadcasting?

Vectorization:
- Perform operations on entire arrays without explicit loops.

Broadcasting:
- Allows operations between arrays of different shapes by automatically expanding dimensions.

In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(12,24).reshape(4,3)

print(a)
print("\n" \
"")
print(b)
print(a+b)  # gives error as dimensions are not same. 

# 4. Working with mathematical formulas.

## 4.1 Sigmoid

```
formula = 1/(1 + e^(-x))
```

In [16]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))


arr = np.arange(12).reshape(3,4)
sigmoid(arr)

array([[0.5       , 0.73105858, 0.88079708, 0.95257413],
       [0.98201379, 0.99330715, 0.99752738, 0.99908895],
       [0.99966465, 0.99987661, 0.9999546 , 0.9999833 ]])

```
Q.Why is sigmoid useful?

Because it converts any real number:

(-∞, +∞)

into:

(0, 1)

```

## 4.2 Means squared error

```
MSE= 1/n ​∑i->n​(yi​−y^​i​)^2

yi = actual value
y^i= predicted value
n = number of samples
```

In [30]:
def mse(actual, predicted):
  return sum((actual - predicted)**2)/len(actual)

actual = np.arange(24,36)
predicted = np.arange(12,24)
# print(actual)
# print(predicted)

mse(actual, predicted)

np.float64(144.0)

# 5. Working with missing values

In [35]:
import numpy as np

In [37]:
a = np.array([1,2,3,np.nan,5])
a

np.isnan(a)

array([False, False, False,  True, False])

In [38]:
a[~np.isnan(a)]

array([1., 2., 3., 5.])

# 6. matrix

A matrix is a 2D array consisting of rows and columns.

In NumPy, matrices are generally represented using 2D arrays.

```
a * b      # element-wise

a @ b      # matrix multiplication
```

In [1]:
import numpy as np 

In [2]:
a = np.matrix([[1,2,3],[4,5,6]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


## 6.1 Arithmatic operations 

In [12]:
a = np.matrix([[1,2,3],[4,5,6]])
b = np.matrix([[4,5,6],[7,8,9]])

In [15]:
print("Matricx a:")
print(a)
print("\n")

print("Matrix b:")
print(b)

Matricx a:
[[1 2 3]
 [4 5 6]]


Matrix b:
[[4 5 6]
 [7 8 9]]


In [17]:
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[4,5,6],[7,8,9]])


print("Array 1st:")
print(c)
print("\n")
print("Array 2nd:")
print(d)

Array 1st:
[[1 2 3]
 [4 5 6]]


Array 2nd:
[[4 5 6]
 [7 8 9]]


### 1) add

In [18]:
print("Matrix addition.")
print(a+b)
print("\n")

print("Array addition")

print(c+b)



Matrix addition.
[[ 5  7  9]
 [11 13 15]]


Array addition
[[ 5  7  9]
 [11 13 15]]


### 2) Substract

In [21]:
print("Matrix substraction:")
print(a-b)

print("\n")
print("Array substraction:")
print(c-d)

Matrix substraction:
[[-3 -3 -3]
 [-3 -3 -3]]


Array substraction:
[[-3 -3 -3]
 [-3 -3 -3]]


### 3) Div

In [22]:
print("Matrix division:")
print(a/b)
print("\n")

print(c/d)

Matrix division:
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]]


[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]]


### 4) Product


```
For matrix multiplication:

(m × n) × (n × p)

Inner dimensions must match.
```

In [31]:
# print(a*b)

print("Array multiplication:")
print(c*d)



Array multiplication:
[[ 4 10 18]
 [28 40 54]]


In [32]:
a = np.matrix([[1,2],[2,4]])
b = np.matrix([[1,2],[2,4]])

print(a)
print(b)

[[1 2]
 [2 4]]
[[1 2]
 [2 4]]


In [33]:
print("Pruduct of matrix:")
print(a*b)

Pruduct of matrix:
[[ 5 10]
 [10 20]]


In [ ]:
print(a@b)
print(a.dot(b))


[[ 5 10]
 [10 20]]
[[ 5 10]
 [10 20]]


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

## 6.2 Matrix functions

### 1) Transpose

In [37]:
a = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
print(a.T)
np.transpose(a)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

### 2) swapaxes

In [46]:
"Example 1"

a = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print()
print(a.swapaxes(0,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


### 3) inverse()

- Not every matrix has an inverse.
```
- Notice:

Row2 = 2 × Row1

Rows are dependent.

Inverse does not exist.
```

A matrix inverse is a matrix that produces the identity matrix when multiplied with the original matrix.

A × A⁻¹ = I

Modern NumPy:

np.linalg.inv(A)

Conditions:

1. Matrix must be square.
2. Determinant must be non-zero.

Related Function:

np.linalg.det()

In [ ]:
"Example 1"

a = np.matrix([[3,4],[2,1]])
print(a)
print()
print(np.linalg.inv(a))


[[3 4]
 [2 1]]

[[-0.2  0.8]
 [ 0.4 -0.6]]


In [ ]:
"Example 2" 

""" Error : rows are dependet."""

a = np.matrix([[1,2],[2,4]])
print(a)
print()
print(np.linalg.inv(a))


### 4)  np.linalg.matrix_power()

Raises a square matrix to a power.

Syntax:

np.linalg.matrix_power(A, n)

Cases:

n > 0
→ Matrix multiplied n times

n = 0
→ Identity Matrix

n < 0
→ Inverse matrix raised to power |n|

Important:

Works only for square matrices.

In [ ]:
"Example 1"

""" For n = 0"""

a = np.matrix([[1,2],[4,5]])
print(a)
print()
print(np.linalg.matrix_power(a,0))

[[1 2]
 [4 5]]

[[1 0]
 [0 1]]


In [51]:
"Example 2"

"""For n > 0"""

a = np.matrix([[1,2],[4,5]])
print(a)
print()
print(np.linalg.matrix_power(a,2))


[[1 2]
 [4 5]]

[[ 9 12]
 [24 33]]


In [52]:
"EExample 3"

"For n < 0"

a = np.matrix([[1,2],[4,5]])
print(a)
print()
print(np.linalg.matrix_power(a,-1))

[[1 2]
 [4 5]]

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


### 5) Determinant

The determinant is a special value calculated from a square matrix.

Notation: det(A) or  |A|

A determinant is a special value associated with a square matrix.

```
Syntax:   np.linalg.det(A)

For 2×2 matrix:

[a b]
[c d]

det = ad - bc
```

Important:

det ≠ 0
→ Inverse exists

det = 0
→ Inverse does not exist
Quick Check


In [53]:
"Example 1"

a = np.matrix([[4,2],[1,2]])

print(a)
print()
print(np.linalg.det(a))

[[4 2]
 [1 2]]

6.0


In [57]:
"Example 2"

b = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print()
print(np.linalg.det(b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

0.0
