# 1. Numpy array vs Python lists

## 1.1 speed

list

In [3]:
a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]

c = []
import time

start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])

end = time.time() - start
end

2.6902852058410645

array

In [ ]:
import numpy as np

In [6]:
c = np.arange(10000000)
d = np.arange(10000000,20000000)

start = time.time()
d = c+d
end = time.time() - start
end

0.04464983940124512

In [ ]:
print(2.69/0.04)

"array is 67 times faster than python list"


67.25


## 1.2 Memory

list

In [8]:
a = [i for i in range(10000000)]

import sys
sys.getsizeof(a)

89095160

In [11]:
b = np.arange(10000000, dtype=np.int32)

sys.getsizeof(b)

40000112

# 2. Advanced Indexing

## 2.1 Fancy indexing

In [14]:
a1 = np.arange(12).reshape(6,2)
a1

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [15]:
"i want 0th, 2nd, 3rd 5th row"

print(a1[[0,2,3,5]])

[[ 0  1]
 [ 4  5]
 [ 6  7]
 [10 11]]


In [16]:
a1[4,1:]

array([9])

In [17]:
a2 = np.arange(27).reshape(3,3,3)
a2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [28]:
a2[:,[0][:]]

array([[[ 0,  1,  2]],

       [[ 9, 10, 11]],

       [[18, 19, 20]]])

## 2.2 Boolean Indexing

## random.randint()

In [35]:
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[31, 62, 66, 44],
       [15, 87, 39,  9],
       [16, 66, 98, 94],
       [99, 21, 10, 22],
       [66, 65, 15, 72],
       [20, 14, 84, 65]], dtype=int32)

In [36]:
a > 50

array([[False,  True,  True, False],
       [False,  True, False, False],
       [False,  True,  True,  True],
       [ True, False, False, False],
       [ True,  True, False,  True],
       [False, False,  True,  True]])

In [38]:
a[a>50]


array([62, 66, 87, 66, 98, 94, 99, 66, 65, 72, 84, 65], dtype=int32)

In [ ]:
"Find out even numbers."

a[a % 2 == 0]

array([62, 66, 44, 16, 66, 98, 94, 10, 22, 66, 72, 20, 14, 84],
      dtype=int32)

In [44]:
"Find out numbers greater than 50 and also even. "

a[(a % 2 == 0) & (a>50)]

array([62, 66, 66, 98, 94, 66, 72, 84], dtype=int32)

In [46]:
a

array([[31, 62, 66, 44],
       [15, 87, 39,  9],
       [16, 66, 98, 94],
       [99, 21, 10, 22],
       [66, 65, 15, 72],
       [20, 14, 84, 65]], dtype=int32)

In [48]:
"Find numbers not divisible by 7."

a[a % 7 == 0]

array([98, 21, 14, 84], dtype=int32)